server:
  port: 8761
spring:
  application:
    name: server-discovery
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    appname: localhost

    